=== Tanisha-Selva/l/xml/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, department, mark)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT mark (#PCDATA)>

=== Tanisha-Selva/l/xml/external_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
    <student>
        <name>Arun</name>
        <department>IT</department>
        <mark>90</mark>
    </student>
    <student>
        <name>Priya</name>
        <department>CSE</department>
        <mark>85</mark>
    </student>
    <student>
        <name>Meena</name>
        <department>ECE</department>
        <mark>92</mark>
    </student>
</students>
